select
    area_name,
    created_at,
    WEATHER_TIME,
    TEMP,
    SENSIBLE_TEMP,
    MAX_TEMP,
    MIN_TEMP,
    HUMIDITY,
    WIND_DIRCT,
    WIND_SPD,
    PRECIPITATION,
    PRECIPITATION_MM,
    PRECPT_TYPE,
    UV_INDEX_LVL,
    UV_INDEX,
    PM25_INDEX,
    PM25,
    PM10_INDEX,
    PM10,
    AIR_IDX,
    AIR_IDX_MVL,
    CURRENT_TIMESTAMP as snapshot_at
from {{ ref('int_city_weather') }}