version: 1

sources:
  - name: raw_data
    schema: raw_data
    database: "{{ env_var('PGDATABASE') }}"
    
    tables:
      - name: realtime_city_data
        description: "서울시 실시간 도시데이터"
      - name: daily_average_air_quality
        description: "서울시 일별 평균 대기오염도 정보"
      - name: list_rainfall_service
        description: "서울시 강우량 정보"
      - name: 3Q_market_info
        description: "서울시 상권 3분기 분석 데이터"
