-- models/staging/stg_seoul_vibe.sql
WITH source AS (
    SELECT * FROM {{ source('raw_data', '3Q_market_info') }}
),

seoul_3Q_market_info AS (
    SELECT
        CAST(STDR_YYQU_CD AS INT) AS STDR_YYQU_CD,
        TRDAR_SE_CD,
        TRDAR_SE_CD_NM,
        CAST(TRDAR_CD AS INT) AS TRDAR_CD,
        TRDAR_CD_NM,
        SVC_INDUTY_CD,
        SVC_INDUTY_CD_NM,
        CAST(THSMON_SELNG_AMT AS BIGINT) AS THSMON_SELNG_AMT,
        CAST(THSMON_SELNG_CO AS INT) AS THSMON_SELNG_CO,
        CAST(MDWK_SELNG_AMT AS BIGINT) AS MDWK_SELNG_AMT,
        CAST(WKEND_SELNG_AMT AS BIGINT) AS WKEND_SELNG_AMT,
        -- 요일 별 매출액
        CAST(MON_SELNG_AMT AS BIGINT) AS MON_SELNG_AMT,
        CAST(TUES_SELNG_AMT AS BIGINT) AS TUES_SELNG_AMT,
        CAST(WED_SELNG_AMT AS BIGINT) AS WED_SELNG_AMT,
        CAST(THUR_SELNG_AMT AS BIGINT) AS THUR_SELNG_AMT,
        CAST(FRI_SELNG_AMT AS BIGINT) AS FRI_SELNG_AMT,
        CAST(SAT_SELNG_AMT AS BIGINT) AS SAT_SELNG_AMT,
        CAST(SUN_SELNG_AMT AS BIGINT) AS SUN_SELNG_AMT,
        -- 시간대 별 매출액
        CAST(TMZON_00_06_SELNG_AMT AS BIGINT) AS TMZON_00_06_SELNG_AMT,
        CAST(TMZON_06_11_SELNG_AMT AS BIGINT) AS TMZON_06_11_SELNG_AMT,
        CAST(TMZON_11_14_SELNG_AMT AS BIGINT) AS TMZON_11_14_SELNG_AMT,
        CAST(TMZON_14_17_SELNG_AMT AS BIGINT) AS TMZON_14_17_SELNG_AMT,
        CAST(TMZON_17_21_SELNG_AMT AS BIGINT) AS TMZON_17_21_SELNG_AMT,
        CAST(TMZON_21_24_SELNG_AMT AS BIGINT) AS TMZON_21_24_SELNG_AMT,
        -- 성별, 연령대별 매출액
        CAST(ML_SELNG_AMT AS BIGINT) AS ML_SELNG_AMT,
        CAST(FML_SELNG_AMT AS BIGINT) AS FML_SELNG_AMT,
        CAST(AGRDE_10_SELNG_AMT AS BIGINT) AS AGRDE_10_SELNG_AMT,
        CAST(AGRDE_20_SELNG_AMT AS BIGINT) AS AGRDE_20_SELNG_AMT,
        CAST(AGRDE_30_SELNG_AMT AS BIGINT) AS AGRDE_30_SELNG_AMT,
        CAST(AGRDE_40_SELNG_AMT AS BIGINT) AS AGRDE_40_SELNG_AMT,
        CAST(AGRDE_50_SELNG_AMT AS BIGINT) AS AGRDE_50_SELNG_AMT,
        CAST(AGRDE_60_ABOVE_SELNG_AMT AS BIGINT) AS AGRDE_60_ABOVE_SELNG_AMT,
        -- 매출 건수
        CAST(MDWK_SELNG_CO AS INT) AS MDWK_SELNG_CO,
        CAST(WKEND_SELNG_CO AS INT) AS WKEND_SELNG_CO,
        CAST(MON_SELNG_CO AS INT) AS MON_SELNG_CO,
        CAST(TUES_SELNG_CO AS INT) AS TUES_SELNG_CO,
        CAST(WED_SELNG_CO AS INT) AS WED_SELNG_CO,
        CAST(THUR_SELNG_CO AS INT) AS THUR_SELNG_CO,
        CAST(FRI_SELNG_CO AS INT) AS FRI_SELNG_CO,
        CAST(SAT_SELNG_CO AS INT) AS SAT_SELNG_CO,
        CAST(SUN_SELNG_CO AS INT) AS SUN_SELNG_CO,
        CAST(TMZON_00_06_SELNG_CO AS INT) AS TMZON_00_06_SELNG_CO,
        CAST(TMZON_06_11_SELNG_CO AS INT) AS TMZON_06_11_SELNG_CO,
        CAST(TMZON_11_14_SELNG_CO AS INT) AS TMZON_11_14_SELNG_CO,
        CAST(TMZON_14_17_SELNG_CO AS INT) AS TMZON_14_17_SELNG_CO,
        CAST(TMZON_17_21_SELNG_CO AS INT) AS TMZON_17_21_SELNG_CO,
        CAST(TMZON_21_24_SELNG_CO AS INT) AS TMZON_21_24_SELNG_CO,
        -- 성별, 연령대별 매출 건수
        CAST(ML_SELNG_CO AS INT) AS ML_SELNG_CO,
        CAST(FML_SELNG_CO AS INT) AS FML_SELNG_CO,
        CAST(AGRDE_10_SELNG_CO AS INT) AS AGRDE_10_SELNG_CO,
        CAST(AGRDE_20_SELNG_CO AS INT) AS AGRDE_20_SELNG_CO,
        CAST(AGRDE_30_SELNG_CO AS INT) AS AGRDE_30_SELNG_CO,
        CAST(AGRDE_40_SELNG_CO AS INT) AS AGRDE_40_SELNG_CO,
        CAST(AGRDE_50_SELNG_CO AS INT) AS AGRDE_50_SELNG_CO,
        CAST(AGRDE_60_ABOVE_SELNG_CO AS INT) AS AGRDE_60_ABOVE_SELNG_CO,
    FROM source
)

SELECT * FROM seoul_3Q_market_info