CREATE TABLE IF NOT EXISTS {SCHEMA_NAME}.{TABLE_NAME} (
    MSRMT_DT VARCHAR(8),
    MSRSTN_NM VARCHAR(50),
    NTDX NUMERIC(10, 4),
    OZON NUMERIC(10, 4),
    CBMX NUMERIC(10, 2),
    SPDX NUMERIC(10, 4),
    PM NUMERIC(10, 2),
    FPM NUMERIC(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MSRMT_DT, MSRSTN_NM)
);
CREATE INDEX IF NOT EXISTS idx_daq_msrmt_dt ON {SCHEMA_NAME}.{TABLE_NAME} (MSRMT_DT);