CREATE TABLE IF NOT EXISTS {SCHEMA_NAME}.{TABLE_NAME} (
    RF_CD INTEGER,
    RF_NM VARCHAR(50),
    GU_CD INTEGER,
    GU_NM VARCHAR(20),
    RN_10M NUMERIC(6, 2),
    DATA_CLCT_TM TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RF_CD, DATA_CLCT_TM)
);
CREATE INDEX IF NOT EXISTS idx_lrs_gu_cd_clct_tm
ON {SCHEMA_NAME}.{TABLE_NAME} (GU_CD, DATA_CLCT_TM DESC, RN_10M DESC);